export enum SocketEvent {
  CreateRoom = "createRoom",
  JoinRoom = "joinRoom",
  LeaveRoom = "leaveRoom",
  StartGame = "startGame",
  RoomCreated = "roomCreated",
  RoomJoined = "roomJoined",
  RoomLeft = "roomLeft",
  PlayerJoined = "playerJoined",
  PlayerLeft = "playerLeft",
  GameStarted = "gameStarted",
  joinRoomError = "joinRoomError",
  RoleAssigned = "roleAssigned",
  NotifyPlayer = "notifyPlayer",
  PlayerNotified = "playerNotified",
}
